version: '3'
services:
  poker-api:    
    build:
      dockerfile: ./Dockerfile.debug.poker-api
    image: poker-api-livedebug
    ports:
    - "9229:9229"
    volumes: 
    - ./src:/app/src
    - ./dist:/app/dist
