version: '3'
services:
  poker-api-base:
    build:
      context: ./
      dockerfile: ./Dockerfile.all.poker-api-base
    image: poker-api-base
  poker-api:    
    build:
      context: ./
      dockerfile: ./Dockerfile.release.poker-api
    image: poker-api
    depends_on:
      - poker-api-base
    networks: 
    - poker-net
    ports:    
    - "3000:3000"
    environment:
      api_port: 3000      

networks: 
  poker-net: 
    driver: bridge